"""Common mask definitions and helpers for the c3a certificate.

Mask M = numerical semigroup <24,26,36,39> intersect [0,189].
B = 189, Q = 2B+1 = 379.
"""
import json
import math


def semigroup_mask(gens, B):
    """Elements of the numerical semigroup generated by gens, intersected with [0,B]."""
    reach = [False] * (B + 1)
    reach[0] = True
    for x in range(B + 1):
        if reach[x]:
            for g in gens:
                if x + g <= B:
                    reach[x + g] = True
    return [x for x in range(B + 1) if reach[x]]


def build_alphabets(M, B):
    """Given mask M (sorted list, subset of [0,B]):
    returns (S, D, kappa) where
      S = sorted set of pairwise sums  (M+M), subset of [0,2B]
      D = sorted set of pairwise differences (M-M), subset of [-B,B]
      kappa[d] = min{a+b : a,b in M, a-b = d}
    """
    Mset = set(M)
    S = sorted({a + b for a in M for b in M})
    kappa = {}
    for a in M:
        for b in M:
            d = a - b
            c = a + b
            if d not in kappa or c < kappa[d]:
                kappa[d] = c
    D = sorted(kappa.keys())
    # sanity: kappa symmetric, parity match
    for d in D:
        assert kappa[d] == kappa[-d], d
        assert (kappa[d] - d) % 2 == 0, d
        alpha = (kappa[d] + d) // 2
        beta = (kappa[d] - d) // 2
        assert alpha in Mset and beta in Mset and alpha - beta == d
    return S, D, kappa


def limit_value(S, D, kappa, Q):
    """Maximize g(lambda) = log sum_d e^{-lam*kappa(d)} - log sum_s e^{-lam*s}
    over lam > 0; limit theta = 1 + g(lam*)/log(Q).
    Returns (lam*, theta_limit, mu, var_d, meta) where
      mu = E_nu[kappa(d)] under nu(d) ~ e^{-lam* kappa(d)}
      var_d = Var_nu[d]  (for the Sigma-d random-walk scale)
    """
    kvals = [kappa[d] for d in D]

    def g(lam):
        zd = sum(math.exp(-lam * k) for k in kvals)
        zs = sum(math.exp(-lam * s) for s in S)
        return math.log(zd) - math.log(zs)

    # golden-section maximize on [0, 0.2]
    lo, hi = 0.0, 0.2
    gr = (math.sqrt(5) - 1) / 2
    a, b = lo, hi
    c1 = b - gr * (b - a)
    c2 = a + gr * (b - a)
    f1, f2 = g(c1), g(c2)
    for _ in range(200):
        if f1 < f2:
            a, c1, f1 = c1, c2, f2
            c2 = a + gr * (b - a)
            f2 = g(c2)
        else:
            b, c2, f2 = c2, c1, f1
            c1 = b - gr * (b - a)
            f1 = g(c1)
    lam = (a + b) / 2
    # tilted stats
    w = [math.exp(-lam * k) for k in kvals]
    Zd = sum(w)
    mu = sum(wi * k for wi, k in zip(w, kvals)) / Zd
    Ed = sum(wi * d for wi, d in zip(w, D)) / Zd
    Ed2 = sum(wi * d * d for wi, d in zip(w, D)) / Zd
    var_d = Ed2 - Ed * Ed
    ws = [math.exp(-lam * s) for s in S]
    Zs = sum(ws)
    mus = sum(wi * s for wi, s in zip(ws, S)) / Zs
    theta = 1 + g(lam) / math.log(Q)
    return lam, theta, mu, var_d, {"E_s": mus, "E_d": Ed, "Zd": Zd, "Zs": Zs,
                                   "g": g(lam)}


# ---- primary mask ----
GENS = (24, 26, 36, 39)
B = 189
Q = 2 * B + 1  # 379


def primary():
    M = semigroup_mask(GENS, B)
    S, D, kappa = build_alphabets(M, B)
    return M, S, D, kappa


if __name__ == "__main__":
    M, S, D, kappa = primary()
    print(f"|M| = {len(M)}  (expect 99)   B = {B}  Q = {Q}")
    print(f"|M+M| = {len(S)}  max s = {max(S)}")
    print(f"|M-M| = {len(D)}  range [{min(D)},{max(D)}]")
    print(f"kappa range: [{min(kappa.values())}, {max(kappa.values())}]")
    lam, theta, mu, var_d, meta = limit_value(S, D, kappa, Q)
    print(f"lambda* = {lam:.8f}")
    print(f"theta_limit = {theta:.10f}   (expect 1.1893936243)")
    print(f"mu = E_nu[kappa] = {mu:.4f}  -> optimal 2L ~ mu*m")
    print(f"E_nu[s] = {meta['E_s']:.4f} (should equal mu at lam*)")
    print(f"sigma_d = {math.sqrt(var_d):.4f}  (Sigma d random-walk scale sqrt(m)*sigma_d)")
    print(f"target  = 1.1835129324, headroom = {theta - 1.1835129324:.10f}")
    with open("mask_primary.json", "w") as f:
        json.dump({"gens": GENS, "B": B, "Q": Q, "M": M, "S": S, "D": D,
                   "kappa": {str(d): kappa[d] for d in D}}, f)
